[build]
builder = "NIXPACKS"
buildCommand = "cd popup-system && echo 'Building from popup-system directory'"

[deploy]
startCommand = "cd popup-system/api && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONPATH = "/app/popup-system"

# Database persistence
[[deploy.volumes]]
mountPath = "/app/popup-system/api/data"
name = "popup-database" 