[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONPATH = "/app"

# Database persistence with proper volume mounting
[[deploy.volumes]]
mountPath = "/app/popup-system/api/data"
name = "popup-database" 